import {
    Home,
    Settings,
    Binary,
    Atom,
    Bot,
    Layers2,
    MonitorDown,
    Wand,
    HardDriveDownload,
    Terminal,
    MonitorCheck,
    WalletCards,
    Info,
    Scale,
    FileText,
    ChartBar,
} from 'lucide-svelte/icons';

export const navigationConfig = writable<NavigationConfig>({
    Home: {
        name: 'Home',
        icon: Home,
        id: 'home',
        title: 'Dashboard',
        description: 'Overview of your workspace and quick access to recent activities.',
        children: [],
    },
    MolecularAnalysis: {
        name: 'Molecule Analysis',
        icon: Atom,
        id: 'molecular_analysis',
        title: 'Molecule Analysis',
        description: 'Explore molecular structures and perform basic chemical analysis.',
        children: [],
    },
    LoadFile: {
        name: 'Load Molecules file',
        icon: MonitorDown,
        id: 'load_file',
        title: 'Load Molecule Files',
        description: 'Import molecular data files and prepare them for further analysis.',
        children: [
            {
                name: 'Load',
                id: 'load_data',
                icon: FileText,
                title: 'Load',
                description: 'Upload and parse molecule datasets for processing.',
            },
            {
                name: 'Analyse',
                id: 'analyse_data',
                icon: ChartBar,
                title: 'Analyse',
                description: 'View summary statistics and initial insights from your dataset.',
            },
        ],
    },
    EmbeddMolecule: {
        name: 'Vectorize Molecules',
        icon: Bot,
        id: 'embedd_molecules',
        title: 'Molecular Vectorization',
        description: 'Generate vector embeddings from molecular structures using advanced encoders.',
        children: [],
    },
    DimenstionalityReduction: {
        name: 'Dimensionality Reduction',
        icon: Layers2,
        id: 'dim_reduction',
        title: 'Dimensionality Reduction',
        description: 'Visualize and explore molecular embeddings in reduced dimensions.',
        children: [
            {
                name: 'PCA',
                id: 'pca_embedder',
                title: 'PCA',
                description: 'Principal Component Analysis for linear dimensionality reduction.',
            },
            {
                name: 'UMAP',
                id: 'umap_embedder',
                title: 'UMAP',
                description: 'Uniform Manifold Approximation for visualizing high-dimensional embeddings.',
            },
            {
                name: 't-SNE',
                id: 'tsne_embedder',
                title: 't-SNE',
                description: 't-distributed Stochastic Neighbor Embedding for clustering and exploration.',
            },
        ],
    },
    MLTraining: {
        name: 'ML Training',
        icon: Binary,
        id: 'ml_training',
        title: 'Machine Learning Training',
        description: 'Build, train, and evaluate ML models on molecular datasets.',
        children: [
            {
                name: 'ML Model',
                id: 'ml_model',
                icon: Binary,
                title: 'ML Model',
                description: 'Configure and train predictive models using molecular features.',
            },
            {
                name: 'ML Prediction',
                id: 'ml_prediction',
                icon: Wand,
                title: 'ML Prediction',
                description: 'Generate predictions from trained models on new molecular inputs.',
            },
        ],
    },
    Settings: {
        name: 'Settings',
        icon: Settings,
        id: 'settings',
        title: 'Application Settings',
        description: 'Configure system preferences and manage your application.',
        children: [
            {
                name: 'Configuration',
                id: 'configuration',
                icon: Settings,
                title: 'Configuration',
                description: 'Customize settings like theme, performance, or storage.',
            },
            {
                name: 'Update',
                id: 'update',
                icon: HardDriveDownload,
                title: 'Update',
                description: 'Check for and apply software updates.',
            },
            {
                name: 'Console',
                id: 'console',
                icon: Terminal,
                title: 'Console',
                description: 'Access system logs and internal console output.',
            },
            {
                name: 'Process-Monitor',
                id: 'process-monitor',
                icon: MonitorCheck,
                title: 'Process Monitor',
                description: 'Monitor background tasks and running jobs.',
            },
            {
                name: 'System',
                id: 'system',
                icon: Info,
                title: 'System',
                description: 'View system information and environment details.',
            },
            {
                name: 'Credit',
                id: 'credit',
                icon: WalletCards,
                title: 'Credit',
                description: 'See contributors and acknowledgments.',
            },
            {
                name: 'License',
                id: 'license',
                icon: Scale,
                title: 'License',
                description: 'Review software licensing terms.',
            },
        ],
    },
});

export const active_page_id = localWritable<string>('active_page_id', 'home');

export const active_page_child_id = localWritable<{ [key in PAGES]: string }>('active_page_child_id', {
    // export const active_page_child_id = writable<{ [key in PAGES]: string }>({
    Home: '',
    MolecularAnalysis: '',
    LoadFile: 'load_data',
    EmbeddMolecule: '',
    DimenstionalityReduction: 'pca_embedder',
    MLTraining: 'ml_model',
    Settings: 'configuration',
});
